version: "3.8"

services:
  app-v1:
    image: <your-dockerhub-username>/yolo-stream:latest
    container_name: yolo-app-v1
    restart: always
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/video_feed"]
      interval: 10s
      retries: 3

  app-v2:
    image: <your-dockerhub-username>/yolo-stream:latest
    container_name: yolo-app-v2
    restart: always
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/video_feed"]
      interval: 10s
      retries: 3
